/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Pessoa;
import Table.TabelaPessoa;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;

public class PessoasPanel extends javax.swing.JPanel {
    private static int idLinha = 0; 
    private final int INSERIR = 1;
    private final int ALTERAR = 2;

    public PessoasPanel() {
        initComponents();
        inicializar();
    }
   
    private static List<Pessoa>lista;    
    private static TabelaPessoa dadosTabela;
    
    private void inicializar(){
        lista = new ArrayList<>();
        dadosTabela = new TabelaPessoa(lista);
        tablePessoa.setModel(dadosTabela);
    }
    
    public static void adicionarNaTabela (Pessoa pessoa){
        dadosTabela.adicionar(pessoa);
    }
    
    public static void deletarNaTabela(int linha)
    {
        dadosTabela.excluir(linha);
    }

    @SuppressWarnings("empty-statement")
    public static void limparTabela()
    {        
        while(tablePessoa.getRowCount() > 0)
        {
            deletarNaTabela(0);
        }
    }

    public static void listarTodosGrid(String campo, String valor)
    {
        limparTabela();
        ArrayList<Pessoa> arrayList = Pessoa.listarTodas(campo, valor);
        
        for(Pessoa pessoa : arrayList)
        {
            dadosTabela.adicionar(pessoa);
        }
    }
    
    private static boolean temLinhaSelecionada()
    {
        if(tablePessoa.getSelectedRow() == -1)
        {
            return false;
        }
        
        else
        {
            return true;
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloPessoas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePessoa = new javax.swing.JTable();
        txtPesquisa = new javax.swing.JTextField();
        bttnPesquisar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        bttnInserir = new javax.swing.JButton();
        bttnAlterar = new javax.swing.JButton();
        bttnExcluir = new javax.swing.JButton();
        comboPesquisa = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTituloPessoas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTituloPessoas.setText("Cadastro de Pessoas");

        tablePessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablePessoa);

        txtPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPesquisaFocusLost(evt);
            }
        });
        txtPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPesquisaMouseClicked(evt);
            }
        });

        bttnPesquisar.setBackground(new java.awt.Color(255, 255, 255));
        bttnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/magnifying-glass (1).png"))); // NOI18N
        bttnPesquisar.setBorderPainted(false);
        bttnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnPesquisarActionPerformed(evt);
            }
        });

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        bttnInserir.setBackground(new java.awt.Color(255, 255, 255));
        bttnInserir.setText("Inserir");
        bttnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnInserirActionPerformed(evt);
            }
        });
        jPanel2.add(bttnInserir);

        bttnAlterar.setBackground(new java.awt.Color(255, 255, 255));
        bttnAlterar.setText("Alterar");
        bttnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAlterarActionPerformed(evt);
            }
        });
        jPanel2.add(bttnAlterar);

        bttnExcluir.setBackground(new java.awt.Color(255, 255, 255));
        bttnExcluir.setText("Excluir");
        bttnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnExcluirActionPerformed(evt);
            }
        });
        jPanel2.add(bttnExcluir);

        comboPesquisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CPF/CNPJ", "Nome(Ativos)", "Nome(Todos)" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTituloPessoas)
                        .addGap(341, 524, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(comboPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bttnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloPessoas)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bttnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPesquisa)
                    .addComponent(comboPesquisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPesquisaMouseClicked
        
    }//GEN-LAST:event_txtPesquisaMouseClicked

    private void txtPesquisaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaFocusLost
        if("".equals(txtPesquisa.getText()))
        {
            txtPesquisa.setText("Pesquisar...");
        }
    }//GEN-LAST:event_txtPesquisaFocusLost

    private void bttnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnPesquisarActionPerformed
        if("Pesquisar...".equals(txtPesquisa.getText()))
        {
            txtPesquisa.setText(null);
        }
        limparTabela();
        listarTodosGrid(comboPesquisa.getSelectedItem().toString(), txtPesquisa.getText());
    }//GEN-LAST:event_bttnPesquisarActionPerformed

    private void bttnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnInserirActionPerformed
        JFrame jFramePessoa = new PessoasCadastro(null, INSERIR);
        jFramePessoa.setTitle("Cadastro de Pessoa - Inserindo");
        jFramePessoa.show();
    }//GEN-LAST:event_bttnInserirActionPerformed

    private void bttnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAlterarActionPerformed
        if(temLinhaSelecionada() == true)
        {
            idLinha = tablePessoa.getSelectedRow();
            Pessoa pessoa = Pessoa.listarUma((int) tablePessoa.getValueAt(idLinha, 0));
            JFrame jFramePessoa = new PessoasCadastro(pessoa, ALTERAR);
            jFramePessoa.setTitle("Cadastro de Pessoa - Alterando");
            jFramePessoa.show();
        }
        
        else
        {
            Helper.MostrarMensagem.mostrarSelecioneUmRegistro();
        }
    }//GEN-LAST:event_bttnAlterarActionPerformed

    private void bttnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnExcluirActionPerformed
        if(temLinhaSelecionada() == true)
        {
            if(Pessoa.deletarPessoa((int) tablePessoa.getValueAt(tablePessoa.getSelectedRow(), 0)))
            {
                Helper.MostrarMensagem.mostrarErroMensagem("Registro excluído com sucesso!");
                idLinha = tablePessoa.getSelectedRow();
                limparTabela();
                listarTodosGrid(comboPesquisa.getSelectedItem().toString(), txtPesquisa.getText());
            }
            
            else
            {
                Helper.MostrarMensagem.mostrarErroMensagem("Falha na exclusão do registro");
            }
        }
        
        else
        {
            Helper.MostrarMensagem.mostrarSelecioneUmRegistro();
        }
    }//GEN-LAST:event_bttnExcluirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnAlterar;
    private javax.swing.JButton bttnExcluir;
    private javax.swing.JButton bttnInserir;
    private javax.swing.JButton bttnPesquisar;
    private javax.swing.JComboBox<String> comboPesquisa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTituloPessoas;
    private static javax.swing.JTable tablePessoa;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
