/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Exception.BancoException;
import Exception.CampoVazioException;
import Exception.ConverterCamposDoubleException;
import Exception.LimiteCampoException;
import Model.Pessoa;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

public class PessoasCadastro extends javax.swing.JFrame {

    private final int INSERIR = 1;
    private final int ALTERAR = 2;
    private int idPessoa = 0;
    private int acaoFrame = 0;
    
    private void receberPessoa(Pessoa pessoa)
    {
        if(pessoa != null)
        {
            idPessoa = pessoa.getIdPessoa();
            this.txtId.setText(String.valueOf(pessoa.getIdPessoa()));
            this.txtRazaoSocial.setText(pessoa.getRazaoSocial());
            
            switch(pessoa.getTipoPessoa())
            {
                case "Física": comboTipoPessoa.setSelectedIndex(0); break;
                case "Jirídica": comboTipoPessoa.setSelectedIndex(1); break;
            }
                    
            String cpfCnpjSemMaskStr = pessoa.getCpfCnpj().replace(".", "");
            cpfCnpjSemMaskStr = cpfCnpjSemMaskStr.replace("/", "");
            cpfCnpjSemMaskStr = cpfCnpjSemMaskStr.replace("-", "");
            cpfCnpjSemMaskStr = cpfCnpjSemMaskStr.replace(" ", "");
            
            this.txtCpfCnpj.setValue(pessoa.getCpfCnpj());
            
            this.dtNascimento.setDate(pessoa.getDataNascimento());
            
            if("Não".equals(pessoa.isAtivo()))
            {
                this.checkAtivo.setSelected(false);
            }
        }
    }
    
    public PessoasCadastro(Pessoa pessoa, int acao) {
        initComponents();
        receberPessoa(pessoa);
        acaoFrame = acao;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        txtRazaoSocial = new javax.swing.JTextField();
        lblTipoPessoa = new javax.swing.JLabel();
        comboTipoPessoa = new javax.swing.JComboBox();
        lblDataNascimento = new javax.swing.JLabel();
        lblCpfCnpj = new javax.swing.JLabel();
        checkAtivo = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        bttnSalvar = new javax.swing.JButton();
        bttnCancelar = new javax.swing.JButton();
        dtNascimento = new com.toedter.calendar.JDateChooser();
        txtCpfCnpj = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Pessoa - Inserindo");
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblId.setText("ID");

        txtId.setEnabled(false);

        lblNome.setText("Nome");

        lblTipoPessoa.setText("Tipo de Pessoa");

        comboTipoPessoa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Física", "Jurídica" }));
        comboTipoPessoa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboTipoPessoaItemStateChanged(evt);
            }
        });
        comboTipoPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoPessoaActionPerformed(evt);
            }
        });

        lblDataNascimento.setText("Data de Nascimento");

        lblCpfCnpj.setText("CPF");

        checkAtivo.setBackground(new java.awt.Color(255, 255, 255));
        checkAtivo.setSelected(true);
        checkAtivo.setText("Ativo");

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        bttnSalvar.setBackground(new java.awt.Color(255, 255, 255));
        bttnSalvar.setText("Salvar");
        bttnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(bttnSalvar);

        bttnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        bttnCancelar.setText("Cancelar");
        bttnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(bttnCancelar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkAtivo))
                        .addComponent(txtRazaoSocial)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNome)
                                .addComponent(lblId))
                            .addGap(34, 34, 34))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTipoPessoa))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCpfCnpj)
                                .addComponent(txtCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblDataNascimento)
                                    .addGap(0, 34, Short.MAX_VALUE))
                                .addComponent(dtNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(checkAtivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNome)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblTipoPessoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(comboTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDataNascimento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCpfCnpj)
                        .addGap(26, 26, 26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void bttnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnSalvarActionPerformed
        
        String razaoSocialStr = txtRazaoSocial.getText();
        String cpfCnpjStr = txtCpfCnpj.getText();
        
        try
        {
            String cpfCnpjSemMaskStr = txtCpfCnpj.getText().replace(".", "");
            cpfCnpjSemMaskStr = cpfCnpjSemMaskStr.replace("/", "");
            cpfCnpjSemMaskStr = cpfCnpjSemMaskStr.replace("-", "");
            cpfCnpjSemMaskStr = cpfCnpjSemMaskStr.replace(" ", "");
            
            Helper.ConverterCamposHelper.validarCampoVazio(lblCpfCnpj.getText(), cpfCnpjSemMaskStr);
            Helper.ConverterCamposHelper.validarCampoVazio("Razáo Social", txtRazaoSocial.getText());
            Helper.ConverterCamposHelper.validarCampoVazio("Data de Nascimento", dtNascimento.getDateFormatString());
            
            Helper.ConverterCamposHelper.validarMaiorQue("Razão Social", razaoSocialStr, 50);
            Helper.ConverterCamposHelper.validarMaiorQue(lblCpfCnpj.getText(), cpfCnpjStr, 20);

            Pessoa pessoa = new Pessoa();
            pessoa.setRazaoSocial(txtRazaoSocial.getText());
            pessoa.setTipoPessoa(comboTipoPessoa.getSelectedItem().toString());
            pessoa.setCpfCnpj(txtCpfCnpj.getText());
            pessoa.setDataNascimento(dtNascimento.getDate());  
            if(checkAtivo.isSelected())
            {
                pessoa.setAtivo("Sim");
            }
            else
            {
                pessoa.setAtivo("Não");
            }
            
            if(acaoFrame == INSERIR && Pessoa.validarSeCpfCnpjExiste(pessoa.getCpfCnpj()) == false)
            {
                pessoa = Pessoa.inserirPessoa(pessoa);
                PessoasPanel.adicionarNaTabela(pessoa);
                this.dispose();
            }

            else if(acaoFrame == INSERIR && Pessoa.validarSeCpfCnpjExiste(pessoa.getCpfCnpj()) == true)
            {
                    Helper.MostrarMensagem.mostrarErroMensagem("Registro já cadastrado!");
            }

            else
            {
                pessoa.setIdPessoa(idPessoa);
                PessoasPanel.limparTabela();
                PessoasPanel.adicionarNaTabela(Pessoa.alterarPessoa(pessoa));
                this.dispose();
            }
        }
        
        catch(ConverterCamposDoubleException | LimiteCampoException | CampoVazioException | BancoException ex)
        {
            Helper.MostrarMensagem.mostrarErroMensagem(ex.getMessage());
        }    
    }//GEN-LAST:event_bttnSalvarActionPerformed

    private void comboTipoPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoPessoaActionPerformed
        validarMask();
    }//GEN-LAST:event_comboTipoPessoaActionPerformed

    private void validarMask()
    {
        try 
        {
            MaskFormatter maskCpf = new MaskFormatter("###.###.###-##");
            MaskFormatter maskCnpj = new MaskFormatter("##.###.###/####-##");
            
            if(comboTipoPessoa.getSelectedIndex() == 0)
            {
                lblCpfCnpj.setText("CPF");
                txtCpfCnpj.setFormatterFactory(new DefaultFormatterFactory(maskCpf));
            }
            
            else if(comboTipoPessoa.getSelectedIndex() == 1)
            {
                lblCpfCnpj.setText("CNPJ");
                txtCpfCnpj.setFormatterFactory(new DefaultFormatterFactory(maskCnpj));
            }
        } 
        catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    private void comboTipoPessoaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTipoPessoaItemStateChanged
        validarMask();
    }//GEN-LAST:event_comboTipoPessoaItemStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        validarMask();
    }//GEN-LAST:event_formWindowOpened

    private void bttnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_bttnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PessoasCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PessoasCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PessoasCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PessoasCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run(Pessoa pessoa, int acao) {
                new PessoasCadastro(pessoa, acao).setVisible(true);
            }
            
            @Override
            public void run() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnCancelar;
    private javax.swing.JButton bttnSalvar;
    private javax.swing.JCheckBox checkAtivo;
    private javax.swing.JComboBox comboTipoPessoa;
    private com.toedter.calendar.JDateChooser dtNascimento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCpfCnpj;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTipoPessoa;
    private javax.swing.JFormattedTextField txtCpfCnpj;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtRazaoSocial;
    // End of variables declaration//GEN-END:variables
}
